//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brightside.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleMetadata
    {
        public int Id { get; set; }
        public int ArticleId { get; set; }
        public string Type { get; set; }
        public string Data { get; set; }
        public bool Success { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
