//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brightside.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BrightsideEntities : DbContext
    {
        public BrightsideEntities()
            : base("name=BrightsideEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<SourceFeed> SourceFeeds { get; set; }
        public virtual DbSet<SourceFeedsHistory> SourceFeedsHistories { get; set; }
        public virtual DbSet<Source> Sources { get; set; }
        public virtual DbSet<ArticleMetadata> ArticleMetadatas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual ObjectResult<SP_NextSourceFeedToGet_Result> SP_NextSourceFeedToGet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_NextSourceFeedToGet_Result>("SP_NextSourceFeedToGet");
        }
    }
}
