//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brightside.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceFeedsHistory
    {
        public long Id { get; set; }
        public int SourceFeedId { get; set; }
        public System.DateTime LastRetrievedTimestamp { get; set; }
    
        public virtual SourceFeed SourceFeed { get; set; }
    }
}
